grmblgrmbl/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
  url( r'^$', views.frontpage, name = 'frontpage' ),
  url( r'^posts$', views.post_list, name = 'post_list' ),
  url( r'^posts/(?P<pid>[0-9]+)$', views.post_detail, name = 'post_detail' ),
  url( r'^feed$', views.feed, name = 'feed' ),
  url( r'^articles$', views.articles, name = 'articles' ),
  url( r'^p(?P<pid>[0-9]+)$', views.shortlink, name = 'shortlink' ),

  url( r'^compose$', views.compose, name = 'compose' ),
]

indieauth/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
  url( r'^$',         views.auth, name = 'authenticate' ),
  url( r'^logout/$',  views.log_out, name = 'logout' ),
]

lanceyspace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

urlpatterns = [
    url(r'^',               include('grmblgrmbl.urls', namespace = "blog")),
    url(r'^auth/',          include('indieauth.urls', namespace = "auth")),
    url(r'^webmention/',   include('webmention.urls', namespace = "webmention")), # Webmention endpoint
    url(r'^admin/',         include(admin.site.urls)),
    url(r'^google7110dd68f0e6bdee.html$', lambda r : render( r, 'google7110dd68f0e6bdee.html') )    # Google verification
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

grmblgrmbl/forms.py
from django import forms

# Create forms below

class ComposeForm ( forms.Form ) :
  """
    Basic form for composing new articles/notes.
    In the future I might separate out these forms based on the media type I'm making, but for now it'll determine the post type based on context.
  """

  title       = forms.CharField( label = "Title", max_length = 100, required = False, help_text = "Leave blank for notes." )
  content     = forms.CharField( label = "Content", widget = forms.Textarea )
  tags        = forms.CharField( label = "Tags", max_length = 200, required = False, help_text = "Separate tags with spaces. #tags will be automatically parsed from notes." )

  reply_to    = forms.URLField( label = "Reply to", max_length = 200, required = False, help_text = "URL this note is a reply to. This should be a permalink. Notes only." )
  reply_name  = forms.CharField( label = "Reply name", max_length = 100, required = False, help_text = "The name to reply to, without an @ (e.g. aaronpk). Notes only." )
  reply_prof  = forms.URLField( label = "Reply profile", max_length = 200, required = False, help_text = "The base site this reply should link to (e.g. http://aaronpareki.com). Notes only.")

  syn_twitter = forms.BooleanField( label = "Post to Twitter", initial = True, required = False )

  delete      = forms.BooleanField( label = "Delete Post", initial = False, required = False, help_text = "If you're editing a post, check this box to delete it instead." )

  post_id     = forms.IntegerField( widget = forms.HiddenInput, required = False )

grmblgrmbl/views.py
from bs4 import BeautifulSoup
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from possem.twitter import tweet_post, delete_post
from possem.twitter_utils import get_selfauthed_api_handler, get_status_id_from_url
from urllib2 import urlopen
from webmention.send import send_webmentions_from_post
from .models import Post, Note, Article, Reply
from .forms import ComposeForm

# Create your views here.

def frontpage ( request ) :
  return post_list( request )

def feed ( request ) :
  return post_list( request, model = Note, page_len = 30 )

def articles ( request ) :
  return post_list( request, model = Article, page_len = 10 )

def post_list ( request, model = Post, page_len = 15 ) :
  # Get page number
  try :
    page  = int( request.GET["page"] )
    start = ( page - 1 ) * page_len
    end   = start + page_len
  except :
    page  = 1
    start = 0
    end   = page_len

  # Get search tags
  try :
    tag   = request.GET["tag"]
    post_list = model.objects.filter( tags__contains = tag ).order_by( '-date_posted' )[start:end]
  except :
    post_list = model.objects.order_by( '-date_posted' )[start:end]
  
  last_page = len( post_list ) < page_len

  return render_to_response( 'grmbl/post_list.html', { 'post_list' : post_list, 'page' : page, 'last_page' : last_page }, context_instance = RequestContext( request ) )

def post_detail ( request, pid ) :
  post    = get_object_or_404( Post, pk = pid )
  tags    = [tag for tag in post.tags.split( " " ) if tag]
  context = {}

  if post.kind() == "Reply" :
    # Try to assemble some sort of reply context
    if "twitter.com" in post.note.reply.reply_url :
      status_id = get_status_id_from_url( post.note.reply.reply_url )

      if status_id :
        api     = get_selfauthed_api_handler()
        status  = api.get_status( status_id )

        context = {
          "avatar"  : status.author.profile_image_url,
          "author"  : status.author.name,
          "title"   : "@" + status.author.screen_name,
          "content" : "<p>" +  status.text + "</p>",
        }
    else :
      # Look at the site's HTML to try to assemble a context
      try :
        soup    = BeautifulSoup( urlopen( post.note.reply.reply_url ).read() )

        hentry  = soup.find( "", { "class" : "h-entry" } )
        if hentry :
          avatar  = soup.find( "", { "class" : "u-logo" } )
          author  = hentry.find( "", { "class" : "p-author" } )
          title   = hentry.find( "", { "class" : "p-name" } )
          summary = hentry.find( "", { "class" : "p-summary" } )
          content = summary if summary else hentry.find( "", { "class" : "e-content" } )

          context = {
            "avatar"   : avatar['src'] if avatar else author.img['src'] if author else "",
            "author"   : author.text if author else "",
            "title"    : title.text if title else "",
            "content"  : content.text if content else "",
          }
        else :
          # Attempt to use meta information for a context
          og_image    = soup.find( "meta", { "property" : "og:image" } )
          og_author   = soup.find( "meta", { "property" : "og:site_name" } )
          og_title    = soup.find( "meta", { "property" : "og:title" } )
          og_descript = soup.find( "meta", { "property" : "og:description" } )

          if og_image or og_author or og_title or og_descript :
            context = {
              "avatar"  : soup.find( "meta", { "property" : "og:image" } )['content'] if og_image else "",
              "author"  : soup.find( "meta", { "property" : "og:site_name" } )['content'] if og_author else "",
              "title"   : soup.find( "meta", { "property" : "og:title" } )['content'] if og_title else "",
              "content" : "<p>" + soup.find( "meta", { "property" : "og:description" } )['content'] + "</p>" if og_descript else "",
            }
      except Exception as e :
        print "Extract meta fail: {}".format( e )

  return render_to_response( 'grmbl/post_detail.html', { 'post' : post, 'tags' : tags, 'reply_context' : context }, context_instance = RequestContext( request ) )

def shortlink( request, pid ) :
  # Shortlinks should just redirect to the valid post
  return HttpResponseRedirect( '/posts/' + str( pid ) )

def compose ( request ) :
  if not request.user.is_authenticated or not request.user.is_staff :
    return HttpResponseForbidden()

  if request.method == "POST" :
    form = ComposeForm( request.POST )

    if form.is_valid() :
      title   = form.cleaned_data['title']
      content = form.cleaned_data['content']
      tags    = form.cleaned_data['tags']

      try :
        post = Post.objects.get( pk = form.cleaned_data['post_id'] )

        if form.cleaned_data['delete'] :
          try :
            if post.posse_data.twitter :
              delete_post( post )
          except Exception as e :
            print e

          post.delete()
          return HttpResponseRedirect( '/' )

        if post.kind() == "Article" :
          post.article.title    = title
          post.article.content  = content
          post.article.tags     = tags

          post.article.save()
        else :
          post.note.content   = content
          post.note.tags      = tags

          if post.kind() == "Reply" :
            post.note.reply.reply_url     = form.cleaned_data['reply_to']
            post.note.reply.display_name  = form.cleaned_data['reply_name']
            post.note.reply.profile       = form.cleaned_data['reply_prof']

            post.note.reply.save()
          else :
            post.note.save()
      except Post.DoesNotExist :
        if title :
          new_article         = Article()
          new_article.title   = title
          new_article.content = content
          new_article.tags    = tags

          new_article.save()
          post = new_article
        else :
          if form.cleaned_data['reply_to'] :
            reply_to    = form.cleaned_data['reply_to']
            reply_name  = form.cleaned_data['reply_name']
            reply_prof  = form.cleaned_data['reply_prof']

            new_reply         = Reply()
            new_reply.content = content
            new_reply.tags    = tags

            new_reply.reply_url     = reply_to
            new_reply.display_name  = reply_name
            new_reply.profile       = reply_prof

            new_reply.save()
            post = new_reply
          else :
            new_note          = Note()
            new_note.content  = content
            new_note.tags     = tags

            new_note.save()
            post = new_note

        if form.cleaned_data['syn_twitter'] :
          tweet_post( post )

      send_webmentions_from_post( post )

      return HttpResponseRedirect( '/posts/' + str( post.pk ) )
  else :
    try :
      if request.GET.has_key( 'post_id' ) :
        post      = Post.objects.get( pk = request.GET['post_id'] )
        
        if post.kind() == "Article" :
          init_data = {
            'title'   : post.article.title,
            'content' : post.article.content,
            'tags'    : post.tags,
          }
        else :
          init_data = {
            'content' : post.note.content,
            'tags'    : post.tags,
          }

          if post.kind() == "Reply" :
            init_data['reply_to']   = post.note.reply.reply_url
            init_data['reply_name'] = post.note.reply.display_name
            init_data['reply_prof'] = post.note.reply.profile

        init_data['post_id']  = post.pk

        form      = ComposeForm( init_data )
      else :
        form      = ComposeForm()
    except Post.DoesNotExist :
      form        = ComposeForm()

  return render_to_response( 'grmbl/compose.html', { 'form' : form }, context_instance = RequestContext( request ) )

grmblgrmbl/templates/grmbl/compose.html
{% extends "grmbl/default.html" %}

{% block content %}
  <form class="compose-form" action="/compose" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
  </form>
{% endblock %}

{% block posthcard %}
{% endblock %}

grmblgrmbl/templates/grmbl/default.html
{% load staticfiles %}

<html>
<head>
  <title>LANCEY SPACE</title>

  <!-- here be icons -->
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="apple-touch-icon-precomposed" href="http://lancey.space/static/lance_logo.png">

  <link rel="stylesheet" href="{% static 'default.css' %}">

  <!-- TODO: host these locally -->
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <link rel="webmention" href="http://lancey.space{% url 'webmention:endpoint' %}">
</head>

<body>
<!-- web-sign-in block -->

{% if user.is_authenticated %}
<div id="websignin">
  <form action="{% url 'auth:logout' %}" method="get">
    <label for="signout_button">SIGNED IN AS {{ user.username }}</label>
    <button id="signout_button" type="submit">Sign Out</button>
  </form>
</div>
{% else %}
<div id="websignin">
  <form action="https://indieauth.com/auth" method="get">
    <label for="indie_auth_url">WEB SIGN IN:</label>
    <input id="indie_auth_url" type="text" name="me" placeholder="example.com">
    <button type="submit">Sign In</button>
    <input type="hidden" name="client_id" value="http://lancey.space">
    <input type="hidden" name="redirect_uri" value="http://lancey.space{% url 'auth:authenticate' %}">
  </form>
</div>
{% endif %}

<div id="wrapper">

  <h1><a href="/">LANCEY SPACE</a></h1>
  
  <div id="navigation">
    <a class="navbutton" href="{% url 'blog:feed' %}"><img src="{% static 'icon_feed.png' %}"><span class="navbutton-label">FEED</span></a>
    <a class="navbutton" href="{% url 'blog:articles' %}"><img src="{% static 'icon_articles.png' %}"><span class="navbutton-label">ARTICLES</span></a>
    {% if user.is_staff %}<a class="navbutton" href="{% url 'blog:compose' %}"><span class="navbutton-label">NEW</span></a>{% endif %}
  </div>

  <hr>

  {% block content %}{% endblock %}

  <div id="footer">
    <hr>

    <div id="footer-content">
      <div rel="author" class="p-author h-card contact-box">
        <a href="http://lancey.space" rel="me" class="u-url"><img class="u-photo" width="64px" height="64px" src="http://lancey.space/static/lance_logo.png">
        <span class="p-name nametag">Lance Coyote</span></a>
      </div>

      <div class="social-box">
        <a href="http://twitter.com/lancecoyote" rel="me"><img class="social-logo" src="{% static 'twitter_logo.png' %}"></a>
        <a href="http://github.com/Lancey6" rel="me"><img class="social-logo" src="{% static 'github_logo.png' %}"></a>
      </div>
    </div>

  </div>
  {% block posthcard %}{% endblock %}
</div>

{% include 'grmbl/google_analytics.html' %}
</body>
</html>

grmblgrmbl/templates/grmbl/post_detail.html
{% extends "grmbl/default.html" %}
{% load staticfiles %}

{% block content %}
  <div class="h-entry">
  <div class="post detail">
    {% if post.article %}<div class="title p-name">{{ post.article.title }}</div>{% endif %}
    {% if user.is_staff %}<div class="meta mod-links"><a href="/compose?post_id={{ post.id }}">Edit / Delete Post</a></div>{% endif %}
    <div class="meta date">
      {% if post.get_previous %}<a href="/posts/{{ post.get_previous.pk }}">Previous</a> - {% endif %}
      Posted on <a class="dt-published u-url" href="/posts/{{ post.pk }}">{{ post.date_posted }}</a>
      {% if post.get_next %} - <a href="/posts/{{ post.get_next.pk }}">Next</a>{% endif %}
    </div>  
    <div class="body">
      {% if post.note.reply %}<div class="meta context">In reply to <a rel="in-reply-to" href="{{ post.note.reply.reply_url }}">{{ post.note.reply.reply_url|truncatechars:60 }}</a></div>
      {% if reply_context %}<div class="ex-context">
        {% if reply_context.avatar %}<img class="context-avatar" src="{{ reply_context.avatar }}">{% endif %}
        <span class="context-title"><a href="{{ post.note.reply.reply_url }}">{{ reply_context.title|truncatechars_html:100 }}</a></span>
        <span class="context-author">{{ reply_context.author }}</span>
        <div class="context-content">
          {{ reply_context.content|safe|truncatewords_html:200 }}
        </div>
      </div>{% endif %}{% endif %}
      {% if post.article %}{{ post.article.content|safe }}{% elif post.note %}{{ post.note.raw_content|safe }}{% endif %}
    </div>
    <div class="discovery">
      <div class="syndication">
        {% if post.posse_data.twitter %}<div class="meta twitter"><a class="u-syndication" rel="syndication" href="{{ post.posse_data.twitter }}">View on Twitter</a></div>{% endif %}
      </div>
      <div class="meta tags">Tags: {% for tag in tags %}<a class="p-category" href="/posts?tag={{ tag }}">#{{ tag }}</a> {% endfor %}</div>
    </div>
    <div class="interaction">
      <div class="actions">
        {% if post.posse_data.twitter %}<span class="meta like"><indie-action do="like" with="http://lancey.space/posts/{{ post.pk }}">
          <a href="https://twitter.com/intent/favorite?tweet_id={{ post.posse_data.get_tweet_id }}"><i class="fa fa-heart fa-fw"></i> Like</a> ({{ post.get_likes.count }})
        </indie-action></span>
        <span class="meta repost"><indie-action do="repost" with="http://lancey.space/posts/{{ post.pk }}">
          <a href="https://twitter.com/intent/retweet?tweet_id={{ post.posse_data.get_tweet_id }}"><i class="fa fa-refresh fa-fw"></i> Repost</a> ({{ post.get_reposts.count }})
        </indie-action></span>
        <span class="meta like"><indie-action do="reply" with="http://lancey.space/posts/{{ post.pk }}">
          <a href="https://twitter.com/intent/tweet?in_reply_to={{ post.posse_data.get_tweet_id }}"><i class="fa fa-reply fa-fw"></i> Reply</a> ({{ post.get_comments.count }})
        </indie-action></span>{% endif %}
      </div>

      <div class="activities">{% for act in post.activity_set.objects.all %}
        {% if act.like %}<div class="act like"><img class="avatar" src="{{ act.like.avatar }}"> liked this</div>
        {% elif act.repost %}<div class="act repost"><img class="avatar" src="{{ act.repost.avatar }}"> reposted this</div>
        {% elif act.comment %}<div class="act comment"><img class="avatar" src="{{ act.comment.avatar }}"> <div class="body">
          <a class="site" href="{{ act.comment.site_url }}">{{ act.comment.site }}</a> <span class="author">{{ act.comment.author }}</span>
          <div class="content">{{ act.comment.content }}</div>
          <a href="{{ act.source }}" class="date">{{ act.comment.date_posted }}</a>
        </div></div>
        {% elif act.mention %}<div class="act mention"><img class="avatar" src="{{ act.mention.avatar }}"> <div class="body">
          <a class="site" href="{{ act.mention.site_url }}">{{ act.mention.site }}</a> <span class="author">{{ act.mention.author }}</span>
          <div class="content"><a href="{{ act.source }}">{{ act.mention.title }}</a></div>
          <a href="{{ act.source }}" class="date">{{ act.mention.date_posted }}</a>
        </div></div>{% endif %}
      {% endfor %}</div>
    </div>
  </div>
{% endblock %}

{% block posthcard %}
</div>
{% endblock %}

grmblgrmbl/templates/grmbl/post_list.html
{% extends "grmbl/default.html" %}

{% block content %}
  <div class="h-feed post-list">
    {% for post in post_list %}
    <div class="h-entry post">
      {% if post.article %}<div class="title"><a class="p-name u-url" href="/posts/{{ post.pk }}">{{ post.article.title }}</a></div>
      <div class="meta date"><a class="dt-published" href="/posts/{{ post.pk }}">{{ post.date_posted }}</a></div>{% endif %}
      <div class="body">
        {% if post.note.reply %}<div class="meta context">In reply to <a rel="in-reply-to" href="{{ post.note.reply.reply_url }}">{{ post.note.reply.reply_url|truncatechars:60 }}</a></div>{% endif %}
        {% if post.article %}{{ post.article.summary|safe|truncatewords:250 }}{% elif post.note %}{{ post.note.raw_content|safe }}{% endif %}
        {% if post.article %}<div class="readmore"><a href="/posts/{{ post.pk }}">Read More...</a></div>{% endif %}
      </div>
      {% if post.note %}<div class="meta date"><a class="dt-published u-url" href="/posts/{{ post.pk }}">{{ post.date_posted }}</a></div>{% endif %}
    </div>
    {% endfor %}
  </div>

  <span class="readmore-link">{% if page > 1 %}<a href="/posts?page={{ page|add:'-1' }}">PREVIOUS</a> - {% endif %}PAGE {{ page }}{% if not last_page %} - <a href="/posts?page={{ page|add:'1' }}">CONTINUE</a>{% endif %}</span>
{% endblock %}